server:
  port: 8090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_CONNECTION-IP:localhost}:${DB_CONNECTION_PORT:5432}/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    generate-ddl: false

  liquibase:
    change-log: db/changelog/db.changelog-master.yml
    enabled: false
    drop-first: true
    default-schema: public